export const indicatorsTableMock = [
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2, // месяц
    value: 120,
    unit_name: '%',
    department_name: 'ГВЦ',
    indicator_type_id: 1,
    link: '',
    diffIndicator: ['▲', '+'],
    chartData: [
      { planValue: 0, actualValue: 110 },
      { planValue: -40, actualValue: 120 },
      { planValue: -100, actualValue: 130 },
      { planValue: 100, actualValue: 140 },
      { planValue: -100, actualValue: 150 },
      { planValue: 0, actualValue: 160 },
      { planValue: 100, actualValue: 170 },
      { planValue: 0, actualValue: 120 }
    ],
    period: 'DD.MM.YYYY - DD.MM.YYYY'
  },
  {
    var_name: 'Выход из строя оборудования',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2, // месяц
    value: 180,
    unit_name: 'шт',
    department_name: 'РЖДТ',
    indicator_type_id: 2,
    link: '',
    diffIndicator: ['▲', '-'],
    chartData: [
      { planValue: 0, actualValue: 50 },
      { planValue: 0, actualValue: 120 },
      { planValue: -5, actualValue: 130 },
      { planValue: -5, actualValue: 140 },
      { planValue: -5, actualValue: 150 },
      { planValue: 5, actualValue: 160 },
      { planValue: 5, actualValue: 170 },
      { planValue: 0, actualValue: 180 }
    ],
    period: 'DD.MM.YYYY - DD.MM.YYYY'
  },
  {
    var_name: 'Простой подвижного состава',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2, // месяц
    value: 10,
    unit_name: '%',
    department_name: 'ЦСС',
    indicator_type_id: 2,
    link: '',
    diffIndicator: ['▲', '-'],
    chartData: [
      { planValue: 0, actualValue: 100 },
      { planValue: -5, actualValue: 100 },
      { planValue: 5, actualValue: 50 },
      { planValue: 5, actualValue: 25 },
      { planValue: -5, actualValue: 10 },
      { planValue: 5, actualValue: 10 },
      { planValue: -5, actualValue: 20 },
      { planValue: 5, actualValue: 10 }
    ],
    period: 'DD.MM.YYYY - DD.MM.YYYY'
  }
]

export const mockData = [
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 11).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 12
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 11).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 12
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 11).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 21
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 11).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 21
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 10).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 12
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 10).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 12
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 10).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 21
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 10).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 21
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 9).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 12
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 9).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 12
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 9).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 21
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 9).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 21
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 200,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 11).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 190,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 11).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 180,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 11).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 170,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 11).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 160,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 10).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 150,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 10).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 140,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 10).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 130,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 10).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 120,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 9).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 110,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 9).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_id: 1,
    value: 100,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 9).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  },
  {
    var_name: 'Укомплектованность персоналом',
    var_type_name: 'Мониторинг',
    indicator_type_name: 'Все',
    date_type_id: 2,
    val_type_name: 'Нарастающий итог по месяцам с начала года',
    value: 90,
    department_name: 'ЦСС',
    indicator_type_id: 1,
    unit_name: 'ед.',
    unit_id: 2,
    department_id: 1,
    date: new Date(2022, 9).toLocaleDateString().split('.').reverse().join('-'),
    metric_type_id: 2
  }
]
